# Modules
- color: "fbca04"
  description: "This issue or pull request is related to cur-report module."
  name: ":floppy_disk: cur-report"
- color: "fbca04"
  description: "This issue or pull request is related to rds-reserved-instance module."
  name: ":floppy_disk: rds-reserved-instance"
