# Modules
- color: "fbca04"
  description: "This issue or pull request is related to cur-report module."
  name: ":floppy_disk: cur-report"
- color: "fbca04"
  description: "This issue or pull request is related to elasticache-reserved-instance module."
  name: ":floppy_disk: elasticache-reserved-instance"
- color: "fbca04"
  description: "This issue or pull request is related to rds-reserved-instance module."
  name: ":floppy_disk: rds-reserved-instance"
- color: "fbca04"
  description: "This issue or pull request is related to savings-plan module."
  name: ":floppy_disk: savings-plan"
